from typing import Any

from pydantic import BaseModel, Field


class JudgePromptTemplate(BaseModel):
    """Template model for configuring LLM Judge prompts and expectations."""

    system_prompt: str = Field(
        ..., description="The system instructions outlining the judge role and context"
    )
    evaluation_instructions: str = Field(
        ..., description="Specific evaluation guidelines for the inputs"
    )
    scoring_rubric: str = Field(
        ..., description="Guidelines for mapping criteria to quantitative scores"
    )
    json_schema_instruction: str = Field(
        default=(
            "You MUST respond ONLY with a valid JSON object matching the following schema:\n"
            "{\n"
            '  "score": float,  // The score based on the rubric\n'
            '  "reasoning": string,  // Step-by-step reasoning explaining the score\n'
            '  "confidence": float  // Your confidence score between 0.0 and 1.0\n'
            "}"
        ),
        description="Instruction enforcing JSON format matching the schema",
    )

    def render_system(self, **kwargs: Any) -> str:
        """Renders the system prompt with variables."""
        return self.system_prompt.format(**kwargs)

    def render_user(self, **kwargs: Any) -> str:
        """Renders the user prompt by combining instructions, rubric, and format constraints."""
        rendered_instructions = self.evaluation_instructions.format(**kwargs)
        prompt = f"{rendered_instructions}\n\n" f"### Scoring Rubric\n" f"{self.scoring_rubric}\n\n"
        if self.json_schema_instruction:
            prompt += f"### Output Format\n{self.json_schema_instruction}"
        return prompt


# Default prompt templates for initial judges

FAITHFULNESS_TEMPLATE = JudgePromptTemplate(
    system_prompt=(
        "You are an expert AI quality assessor. Your task is to evaluate whether "
        "the final response generated by an AI assistant is completely faithful "
        "to the provided context snippets and does not contain any hallucinated, "
        "unsupported, or fabricated details."
    ),
    evaluation_instructions=(
        "Analyze the provided retrieved context snippets and compare them against "
        "the assistant response. Determine if every fact, date, name, and claim in "
        "the response is directly supported by the context snippets. Ignore minor formatting "
        "or style differences.\n\n"
        "Retrieved Context:\n{context}\n\n"
        "Assistant Response:\n{response}"
    ),
    scoring_rubric=(
        "Award a score of 1.0 if the response is completely faithful and contains "
        "no unsupported claims. Award a score of 0.0 if there is even one unsupported "
        "claim, hallucination, or contradiction in the response."
    ),
)

GROUNDEDNESS_TEMPLATE = JudgePromptTemplate(
    system_prompt=(
        "You are an expert AI quality assessor. Your task is to evaluate whether "
        "the final response generated by an AI assistant directly addresses the user "
        "query and adheres to all specified user constraints."
    ),
    evaluation_instructions=(
        "Evaluate the assistant response based on the user query and the constraints "
        "specified below. Identify if the assistant missed any key constraints or failed "
        "to answer the query itself.\n\n"
        "User Query:\n{query}\n\n"
        "Constraints:\n{constraints}\n\n"
        "Assistant Response:\n{response}"
    ),
    scoring_rubric=(
        "Award a score of 1.0 if the response fully answers the query and respects "
        "all constraints. Award a score of 0.0 if the response violates any constraint "
        "or fails to answer the user query."
    ),
)

CORRECTNESS_TEMPLATE = JudgePromptTemplate(
    system_prompt=(
        "You are an expert AI quality assessor. Your task is to evaluate the factual "
        "and semantic correctness of an assistant's response by comparing it against "
        "a reference expected output."
    ),
    evaluation_instructions=(
        "Compare the assistant response against the expected reference output. Check "
        "if the core answer matches the ground truth. Score the alignment on a scale of "
        "0.0 to 1.0.\n\n"
        "User Query:\n{query}\n\n"
        "Expected Reference Output:\n{expected_output}\n\n"
        "Assistant Response:\n{response}"
    ),
    scoring_rubric=(
        "1.0: Response matches reference expected output perfectly in facts and semantics.\n"
        "0.5: Response contains correct core facts but has minor omissions or details.\n"
        "0.0: Response is completely incorrect, irrelevant, or contradicts the expected output."
    ),
)

HALLUCINATION_TEMPLATE = JudgePromptTemplate(
    system_prompt=(
        "You are an expert AI safety auditor. Your task is to scan an AI assistant's "
        "response specifically for any factual hallucinations, fabricated facts, or "
        "unsupported details compared to the ground truth context."
    ),
    evaluation_instructions=(
        "Analyze the response to check if it contains any fabricated facts or information "
        "not explicitly mentioned in the context. Be strict: even plausible-sounding "
        "unsupported details must be flagged as hallucinations.\n\n"
        "Retrieved Context:\n{context}\n\n"
        "Assistant Response:\n{response}"
    ),
    scoring_rubric=(
        "Award a score of 1.0 if the response is completely hallucination-free. "
        "Award a score of 0.0 if the response contains any hallucinated, fabricated, "
        "or context-contradicting statements."
    ),
)
